In [2]:
import torch
import numpy as np

In [15]:
#Create a random tensor with shape (7, 7)

tens1=torch.rand(size=(7,7))
tens1.shape

torch.Size([7, 7])

In [18]:
#Perform a matrix multiplication on the tensor from 2 with another
#random tensor with shape (1,7)

tens2=torch.rand(size=(1,7))

torch.matmul(tens1,tens2.T)

tensor([[1.1791],
        [1.9761],
        [1.7247],
        [1.2421],
        [1.6007],
        [1.6962],
        [1.1644]])

In [24]:
#Set the random seed to 0 and do 2 & 3 over again
torch.manual_seed(0)
tens1=torch.rand(7,7)
tens2=torch.rand(1,7)

Z=torch.matmul(tens1,tens2.T)
Z,Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
torch.cuda.manual_seed(123)
#couldn't find it on the docs

In [28]:
torch.manual_seed(1234)
tens_a=torch.rand(2,3).to("cuda")
tens_b=torch.rand(2,3).to("cuda")
#for some reason the output changes if i write torch.cuda.manual_seed(123)
tens_a,tens_b

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [31]:
Z=torch.matmul(tens_a,tens_b.T)
Z,Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [33]:
Z.max(),Z.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [34]:
Z.argmax(),Z.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [35]:
torch.manual_seed(7)
tens_c=torch.rand(1,1,1,10)
tens_c_squeezed=tens_c.squeeze()
print(tens_c,tens_c.shape,tens_c_squeezed,tens_c_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10]) tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
