In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0


In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.Tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [14]:
TENSOR[0][1][1]

tensor(6.)

In [18]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[2.3453e-03, 5.2296e-01, 3.0339e-01, 5.3572e-01],
        [5.1155e-01, 7.8983e-01, 3.5848e-01, 6.0220e-01],
        [8.9911e-01, 7.3885e-01, 9.5610e-01, 2.8461e-04]])

In [19]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [25]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones=torch.ones(3,4)
ones.dtype

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
#use torch.range() , range will be removed
one_to_ten=torch.arange(0,10,0.2)
one_to_ten

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [40]:
# creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [43]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [44]:
float_32_tensor.dtype

torch.float32