In [18]:
import torch
import numpy as np

In [19]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [21]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [22]:
x[0,0,0]

tensor(1)

In [23]:
x[:,0,:3]

tensor([[1, 2, 3]])

In [24]:
#going from numpy to pytorch changes to dtype of tensor to float64
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [25]:
# Change the value of array, what will this do to 'tensor'?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))