In [1]:
import torch
import numpy as np

In [2]:
x=torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [3]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
x[0][0],x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [5]:
x[0,0,0]

tensor(1)

In [6]:
x[:,0,:3]

tensor([[1, 2, 3]])

In [7]:
#going from numpy to pytorch changes to dtype of tensor to float64
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [8]:
# Change the value of array, what will this do to 'tensor'?
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [9]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [110]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.4800, 0.3480, 0.9293, 0.3343],
        [0.0346, 0.8793, 0.2706, 0.6033],
        [0.0760, 0.5284, 0.1883, 0.2929]])
tensor([[0.7447, 0.0634, 0.3635, 0.7073],
        [0.1377, 0.1140, 0.0909, 0.0339],
        [0.7697, 0.1335, 0.3822, 0.7528]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [113]:
#set the random seet to make random but reproducible tensors,
#these results are completeley same with tutorial
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)  #need to call it after every block
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
