In [1]:
#Reshaping , stacking , squeezing and unsqueezing tensors
import torch
x= torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [10]:
#add an extra dimension
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [11]:
#chaning z will change x , a view shares the same memory
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [16]:
#stack tensors on top of each other
#vstack uses 1 and hstack uses 0 as dim
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [19]:
x_reshaped.shape

torch.Size([9, 1])

In [20]:
#torch.squeeze() - removes all single dimensions
x_reshaped.squeeze().shape

torch.Size([9])