In [40]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0


In [41]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [42]:
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [43]:
vector.shape

torch.Size([2])

In [44]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [45]:
MATRIX.ndim

2

In [46]:
MATRIX[1]

tensor([ 9, 10])

In [47]:
MATRIX.shape

torch.Size([2, 2])

In [48]:
# Tensor
TENSOR = torch.Tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [49]:
TENSOR[0][1][1]

tensor(6.)

In [50]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0390, 0.6838, 0.0464, 0.0244],
        [0.1156, 0.6219, 0.2848, 0.3437],
        [0.9358, 0.2337, 0.6914, 0.7218]])

In [51]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [52]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [53]:
ones=torch.ones(3,4)
ones.dtype

torch.float32

In [54]:
#use torch.range() , range will be removed
one_to_ten=torch.arange(0,10,0.2)
one_to_ten

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [55]:
# creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [56]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [57]:
float_32_tensor.dtype

torch.float32

In [58]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.6613, 0.8015, 0.8906, 0.7549],
        [0.0209, 0.8674, 0.3634, 0.6699],
        [0.0625, 0.4023, 0.2598, 0.2385]])

In [59]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6613, 0.8015, 0.8906, 0.7549],
        [0.0209, 0.8674, 0.3634, 0.6699],
        [0.0625, 0.4023, 0.2598, 0.2385]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [60]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [61]:
tensor*tensor

tensor([1, 4, 9])

In [62]:
#matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [63]:
tensor @ tensor

tensor(14)

In [64]:
#it can be 3,2 2,3 or 2,3 3,2 but not 3,2 3,2 or 2,3 2,3 

torch.matmul(torch.rand(4,2),torch.rand(2,4))

tensor([[0.4835, 0.0876, 1.4246, 0.7722],
        [0.4975, 0.0976, 1.0019, 0.5326],
        [0.4363, 0.0827, 1.0592, 0.5691],
        [0.1946, 0.0284, 1.0014, 0.5525]])

In [66]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#We need to transpose one of the tensors to multiply them.

torch.matmul(tensor_A,tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)