In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.0.0


In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
vector =torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.shape

torch.Size([2])

In [6]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [7]:
MATRIX.ndim

2

In [8]:
MATRIX[1]

tensor([ 9, 10])

In [9]:
MATRIX.shape

torch.Size([2, 2])

In [10]:
# Tensor
TENSOR = torch.Tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR

tensor([[[1., 2., 3.],
         [3., 6., 9.],
         [2., 4., 5.]]])

In [11]:
TENSOR[0][1][1]

tensor(6.)

In [12]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1264, 0.0108, 0.2097, 0.5019],
        [0.5827, 0.3283, 0.8073, 0.4119],
        [0.7385, 0.4981, 0.5074, 0.0645]])

In [13]:
# Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [14]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones=torch.ones(3,4)
ones.dtype

torch.float32

In [16]:
#use torch.range() , range will be removed
one_to_ten=torch.arange(0,10,0.2)
one_to_ten

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000, 1.4000, 1.6000,
        1.8000, 2.0000, 2.2000, 2.4000, 2.6000, 2.8000, 3.0000, 3.2000, 3.4000,
        3.6000, 3.8000, 4.0000, 4.2000, 4.4000, 4.6000, 4.8000, 5.0000, 5.2000,
        5.4000, 5.6000, 5.8000, 6.0000, 6.2000, 6.4000, 6.6000, 6.8000, 7.0000,
        7.2000, 7.4000, 7.6000, 7.8000, 8.0000, 8.2000, 8.4000, 8.6000, 8.8000,
        9.0000, 9.2000, 9.4000, 9.6000, 9.8000])

In [17]:
# creating tensors like
ten_zeros=torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [18]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [19]:
float_32_tensor.dtype

torch.float32

In [20]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2348, 0.9487, 0.9034, 0.8759],
        [0.2501, 0.9089, 0.9833, 0.4485],
        [0.1206, 0.2540, 0.8527, 0.9225]])

In [21]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2348, 0.9487, 0.9034, 0.8759],
        [0.2501, 0.9089, 0.9833, 0.4485],
        [0.1206, 0.2540, 0.8527, 0.9225]])
Datatype of tensor:torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [22]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [23]:
tensor*tensor

tensor([1, 4, 9])

In [24]:
#matrix multiplication
torch.matmul(tensor, tensor)


tensor(14)

In [25]:
tensor @ tensor

tensor(14)

In [26]:
#it can be 3,2 2,3 or 2,3 3,2 but not 3,2 3,2 or 2,3 2,3 

torch.matmul(torch.rand(4,2),torch.rand(2,4))

tensor([[0.2486, 0.6174, 0.7261, 0.2668],
        [0.4501, 0.4925, 0.6081, 0.4610],
        [0.5303, 0.3901, 0.5016, 0.5364],
        [0.3277, 0.5064, 0.6097, 0.3408]])

In [33]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])
#We need to transpose one of the tensors to multiply them.

torch.matmul(tensor_A,tensor_B.T)


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [34]:
x= torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [39]:
#torch.mean function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32))

tensor(45.)

In [42]:
#find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [44]:
#returns the index of min or max
x.argmax()

tensor(9)